/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_mobile_analytics_app_id: "11e4faa463bf4ad4a4724fd406e71168",
  aws_mobile_analytics_app_region: "ap-south-1",
  Analytics: {
    AWSPinpoint: {
      appId: "11e4faa463bf4ad4a4724fd406e71168",
      region: "ap-south-1",
    },
  },
  aws_appsync_graphqlEndpoint:
    "https://pogjt6ntkvdb7gjbhfxfqkxidu.appsync-api.ap-south-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-south-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-t3l3ygaho5erlaypt27r6vjz5u",
  aws_cloud_logic_custom: [
    {
      name: "healthrestapi",
      endpoint:
        "https://g7hlrlv1wh.execute-api.ap-south-1.amazonaws.com/develop",
      region: "ap-south-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "ap-south-1:549647da-4eae-43fd-a7b7-b659b69be666",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_MakqxH3dS",
  aws_user_pools_web_client_id: "2uiusjlk3da9sperajkkscvqk4",
  oauth: {},
  aws_cognito_username_attributes: ["PHONE_NUMBER"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["MIDDLE_NAME", "GIVEN_NAME", "NAME"],
  aws_cognito_mfa_configuration: "ON",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["PHONE_NUMBER"],
  aws_user_files_s3_bucket: "healthstaticbucket92130-develop",
  aws_user_files_s3_bucket_region: "ap-south-1",
};

export default awsmobile;
