/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-south-1",
  aws_mobile_analytics_app_id: "25ab4f599c5c4379a78578967f147a82",
  aws_mobile_analytics_app_region: "ap-south-1",
  Analytics: {
    AWSPinpoint: {
      appId: "25ab4f599c5c4379a78578967f147a82",
      region: "ap-south-1",
    },
  },
  aws_appsync_graphqlEndpoint:
    "https://7gkdtn3sqvfd3n3gcxug3jisxy.appsync-api.ap-south-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-south-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-63elbatchfbthkymg3o6eju67a",
  aws_cloud_logic_custom: [
    {
      name: "healthrestapi",
      endpoint: "https://atwd9qofqh.execute-api.ap-south-1.amazonaws.com/test",
      region: "ap-south-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "ap-south-1:792716f5-362a-42ca-bf21-fe2ce29ac254",
  aws_cognito_region: "ap-south-1",
  aws_user_pools_id: "ap-south-1_JP8Cie1XV",
  aws_user_pools_web_client_id: "3m3lqmtp08uu645d6g5fi7928u",
  oauth: {},
  aws_cognito_username_attributes: ["PHONE_NUMBER"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["MIDDLE_NAME", "GIVEN_NAME", "NAME"],
  aws_cognito_mfa_configuration: "ON",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["PHONE_NUMBER"],
  aws_user_files_s3_bucket: "healthstaticbucket144237-test",
  aws_user_files_s3_bucket_region: "ap-south-1",
};

export default awsmobile;
